### PR TITLE
Add "uknown_client_reject_reason"

### PR DESCRIPTION
**Pull request by DabeDotCom**
See this thread from August 2009:
- http://postfix.1071664.n5.nabble.com/Configurable-replies-for-hardcoded-REJECTS-tp36222p36227.html

### CODE REVIEW

**Comment by vdukhovni** [comment]
This has become rather old.  Are you still hoping to see this merged?

**Comment by DabeDotCom** [comment]
In a perfect world, sure!

The changes in this patch — although based on 2.6 — are pretty trivial, and only *add* functionality, so they're not likely to break a whole lot.

If you'd rather I submit a fresh PR based on the latest 3.3 codebase, I can do that, too...

**Comment by vdukhovni** [comment]
> @DabeDotCom If you'd rather I submit a fresh PR based on the latest 3.3 codebase, I can do that, too...

A fresh PR would be good, but to save you the trouble, perhaps first post to postfix-users or postfix-devel and gauge Wietse's appetite for adopting a patch along these lines...

**Comment by Neustradamus** [comment]
@vdukhovni, @DabeDotCom: Any news?

**Pull request closed without merging**
